services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_net
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    secrets:
      - wp_passwords
      - db_password
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception_net:
    driver: bridge

secrets:
   db_password:
     file: ../secrets/db_password.txt
   db_root_password:
     file: ../secrets/db_root_password.txt
   wp_passwords:
     file: ../secrets/credentials.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aelmsafe/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aelmsafe/data/wordpress
